name: Deploy frontend to Yandex Object Storage
on:
  push:
    branches: [ main ]
    paths:
      - "index.html"
      - "help.html"
      - "app.js"
      - "app.css"
      - "config.js"
      - "favicon*"
      - ".github/workflows/deploy-front.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Сделали апдейт

      # Устанавливаем AWS CLI (v1) через pip в $HOME/.local/bin
      - name: Install AWS CLI
        run: |
          python3 -m pip install --upgrade --user pip awscli
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Check AWS CLI
        run: aws --version

      - name: Sync to Object Storage (S3 compatible)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}   # ru-central1
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET }} \
            --endpoint-url ${{ vars.S3_ENDPOINT }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "prod/*" \
            --exclude "users/*"